[build]
  # Build command for static site generation
  command = "python build_static.py"
  # Directory to publish
  publish = "dist"
  
  # Environment variables
  [build.environment]
    PYTHON_VERSION = "3.11"
    NODE_VERSION = "18"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Functions configuration (if using serverless functions)
[functions]
  directory = "netlify/functions"
